apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
spec:
  secretName: mongo-express-cert-key
  duration: 1h
  renewBefore: 10m
  dnsNames:
  - mongoexpress.deepakdev.live
  - grafana.deepakdev.live
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io