apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-db-configmap
data:
  MONGO_INITDB_ROOT_USERNAME: "kannan"
  MONGO_INITDB_ROOT_PASSWORD: "kannanpass"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db-deploy
  template:
    metadata:
      labels:
        app: mongo-db-deploy
    spec:
      containers:
      - name: mongo-db-deploy
        image: mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-db-configmap
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mongo-db-configmap
              key: MONGO_INITDB_ROOT_PASSWORD
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"


---

apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
spec:
  selector:
    app: mongo-db-deploy
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017