apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-persistent-volume-claim
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi