apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-db-persistent-volume
spec:
  storageClassName: default
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"